# Generated by Django 5.1.7 on 2025-05-11 14:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='time. Format: DD/MM/YYYY/H:M:SS')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='time. Format: DD/MM/YYYY/H:M:SS')),
                ('description', models.TextField(help_text='General description about the company or service.')),
                ('who_we_are', models.TextField(help_text='Detailed description of who you are as a company.')),
                ('name', models.CharField(help_text='Company or website name.', max_length=255)),
                ('logo', models.ImageField(help_text='Required company logo.', upload_to='images/logos')),
                ('cover_images', models.JSONField(blank=True, default=list, help_text='list of cover images URLs')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='time. Format: DD/MM/YYYY/H:M:SS')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='time. Format: DD/MM/YYYY/H:M:SS')),
                ('name', models.CharField(help_text='Package name', max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Amount of The Trip', max_digits=8)),
                ('disassembly_and_assembly', models.BooleanField(default=True, help_text='Disassembly and Assembly included')),
                ('furniture_wrapping', models.BooleanField(default=True, help_text='Unlimited Cardboards (Boxes) included')),
                ('packing_the_belongings', models.BooleanField(default=True, help_text='Packing the Belongings included')),
                ('wrapping_before_packing', models.BooleanField(default=True, help_text='Wrapping before Packing included')),
                ('unpacking_and_organizing', models.BooleanField(default=True, help_text='Unpacking and organizing in your new house included')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['price'],
            },
        ),
    ]
